"""removed a foreign key

Revision ID: 276b9fa4b399
Revises: b89d6ad4edaf
Create Date: 2021-08-29 15:10:14.736252

"""

# revision identifiers, used by Alembic.
revision = '276b9fa4b399'
down_revision = 'b89d6ad4edaf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_user_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_user_id_fkey', 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
