"""added a bio column

Revision ID: 516122125619
Revises: 982880b906dd
Create Date: 2021-08-29 20:18:04.536447

"""

# revision identifiers, used by Alembic.
revision = '516122125619'
down_revision = '982880b906dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
