"""Initial Migration

Revision ID: 6fcd7e0ce1f0
Revises: a2947da74856
Create Date: 2021-08-26 07:50:25.865529

"""

# revision identifiers, used by Alembic.
revision = '6fcd7e0ce1f0'
down_revision = 'a2947da74856'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
