"""returned the foreign key

Revision ID: 9e8f72c71fae
Revises: faa5304a2920
Create Date: 2021-08-29 15:15:16.384227

"""

# revision identifiers, used by Alembic.
revision = '9e8f72c71fae'
down_revision = 'faa5304a2920'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_user_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_user_id_fkey', 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
