"""returned the foreign key

Revision ID: faa5304a2920
Revises: 276b9fa4b399
Create Date: 2021-08-29 15:11:41.876737

"""

# revision identifiers, used by Alembic.
revision = 'faa5304a2920'
down_revision = '276b9fa4b399'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###
